sudo: required

services:
  - docker

before_install:
  - docker build -t smartdockerimage/docker-react -f Dockerfile.dev . 

script:
  - docker run smartdockerimage/docker-react npm run test -- --coverage  

before_deploy:
  - ssh-agent -k 

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-441154321604"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
    

